[versions]

[libraries]
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version = "0.15.11" }
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version = "0.99.4+1.20.6" }

[plugins]
fabric-loom = { id = "fabric-loom", version = "1.6.11" }
lombok = { id = "io.freefair.lombok", version = "8.6"}
spotbugs-base = { id = "com.github.spotbugs-base", version = "6.0.14" }
spotless = { id = "com.diffplug.spotless", version = "6.25.0" }
modmuss50-publish = { id = "me.modmuss50.mod-publish-plugin", version = "0.5.1" }